### PR TITLE
php8 [WIP]

### PR DESCRIPTION
**Pull request by GameHerobrine**

### CODE REVIEW

**Comment by GameHerobrine** [comment]
+12,676 −13,712 oof

**Comment by GameHerobrine** [comment]
hm merge?

**Comment by GameHerobrine** [comment]
<@790706391656431678> nya~~ *or later*

**Comment by GameHerobrine** [comment]
hm actually wonder did it really ping him

**Comment by GameHerobrine** [comment]
<@817721778952601600>

**Comment by GameHerobrine** [comment]
eh nope

**Comment by realfreehij** [comment]
> <@790706391656431678> nya~~ _or later_

когда всё сделаем

**Comment by GameHerobrine** [comment]
new commit by freehij o=

**Comment by GameHerobrine** [comment]
soon: properties fix
*wait actually never*



*i will just move motd and other stuff inside yml*

**Pull request merged**
