### PR TITLE
Unify the code style

### PR DESCRIPTION
**Pull request by Sunch233**
This PR introduces the php cs fixer tool to automatically format code

- You can change the code style of the entire core by modifying the configuration file
- You can use Github CI checking to prevent others from contributing code with incorrect style

------

about the global functions and constants, you can see [pmmp commit 4b9a142](https://github.com/pmmp/PocketMine-MP/commit/4b9a142a5d9d5bfa8f2097b5414fa49d8b6991c1) for details

### CODE REVIEW

**Comment by Sunch233** [comment]
wait a second

**Comment by Sunch233** [comment]
Request to merge

**Comment by GameHerobrine** [comment]
doesnt seem to be very consistent, some files use 4 whitespaces, some files use tabs(bigger part), some mix them

**Comment by Sunch233** [comment]
My mistake. Accidentally comment out the indentation check

**Pull request merged**
